spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: http://keycloak:8080/realms/clockwise/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/clockwise/protocol/openid-connect/token
            jwk-set-uri: http://keycloak:8080/realms/clockwise/protocol/openid-connect/certs
            user-info-uri: http://keycloak:8080/realms/clockwise/protocol/openid-connect/userinfo
        registration:
          keycloak:
            client-id: auth-service
            client-secret: v8Sac9YQKLm0ZrGiS9JgwLRMa4Q0pF7c
            authorization-grant-type: password
            scope:
              - openid
              - profile
              - email
              - roles
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/clockwise
          jwk-set-uri: http://keycloak:8080/realms/clockwise/protocol/openid-connect/certs
  
  application:
    name: auth-service
  
  # R2DBC configuration - uses auth-postgres for Docker
  r2dbc:
    url: r2dbc:postgresql://auth-postgres:5432/auth_db
    username: postgres
    password: password
    
  flyway:
    url: jdbc:postgresql://auth-postgres:5432/auth_db
    user: postgres
    password: password
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

# Keycloak Configuration
keycloak:
  server-url: http://keycloak:8080
  realm: clockwise
  admin:
    client-id: admin-cli
    username: admin
    password: admin

# Kafka Topics
kafka:
  topic:
    user-registration: user-registration-events

# Logging
logging:
  level:
    com.clockwise.authService: DEBUG
    org.springframework.security: DEBUG